---
# tasks file for docker
- name: create image docker
  docker_image:
    name: mohamedbenmiled/devops:latest
    build:
     path: /var/lib/jenkins/workspace/Pipeline_CD
     pull: no
    source: build
    state: present
    force_source: true
- name: run container docker
  docker_container:
    name: myapp_container
    image: mohamedbenmiled/devops:latest
    state: started
    recreate: true
    ports:
     - "4200:80"
